spring:
  profiles:
    active: local
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
config:
  pageSize: 1000
---

spring:
  profiles: local

mysql:
  host: localhost
  schema: sampleservice?serverTimezone=UTC&useServerPrepStmts=false&rewriteBatchedStatements=true
  port: 3306
  user: root
  password: example

rabbitmq:
  username: "guest"
  password: "guest"
  hostname: "localhost"