version: "2.1"
services:
  db:
    image: mysql:5.7.23
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sampleservice
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      TZ: UTC
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
